apiVersion: v1
kind: Namespace
metadata:
  name: crowdsec
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://github.com/marc0777/infra.git
    path: charts/crowdsec
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: crowdsec
  syncPolicy:
    automated:
      selfHeal: true
