apiVersion: v1
kind: Namespace
metadata:
  name: gio
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gio-app
  namespace: gio
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: gio
  source:
    repoURL: https://github.com/giorgia22/GioOps.git
    path: gio-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: gio
  syncPolicy:
    automated:
      selfHeal: true
