apiVersion: v1
kind: Namespace
metadata:
  name: homelab
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-app
  namespace: homelab
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://github.com/marc0777/homelab.git
    path: homelab-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab
  syncPolicy:
    automated:
      selfHeal: true
