apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app
  namespace: infra
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://github.com/marc0777/infra.git
    path: charts/infra-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      selfHeal: true
