apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure project
  sourceRepos:
  - https://github.com/marc0777/infra.git
  sourceNamespaces:
  - infra
  destinations:
  - namespace: '*'
    name: in-cluster
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
