apiVersion: v1
kind: Namespace
metadata:
  name: pnogo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pnogo-app
  namespace: pnogo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: pnogo
  source:
    repoURL: https://github.com/Pnogo/operations.git
    path: pnogo-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: pnogo
  syncPolicy:
    automated:
      selfHeal: true
