apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fincato-pnogo-wildcard
  namespace: traefik
spec:
  secretName: fincato-pnogo-wildcard-tls
  dnsNames:
    - "*.fincato.net"
    - "*.pnogo.dev"
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer