apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure
spec:
  insecureSkipVerify: true
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-redirect
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: insecure@kubernetescrds
spec:
  ports:
  - port: 443
    targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nginx-redirect
subsets:
  - addresses:
      - ip: 10.0.0.100
    ports:
      - port: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: nginx-redirect
spec:
  defaultBackend:
    service:
      name: nginx-redirect
      port:
        number: 443