apiVersion: v1
kind: Service
metadata:
  name: nginx-redirect
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nginx-redirect
subsets:
  - addresses:
      - ip: 10.0.0.100
    ports:
      - port: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: nginx-redirect
spec:
  defaultBackend:
    service:
      name: nginx-redirect
      port:
        number: 80