apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: opnsense
spec:
  bgpInstances:
    - name: "instance-64513"
      localASN: 64513
      peers:
        - name: "peer-64512-opnsense"
          peerASN: 64512
          peerAddress: 10.0.0.1
---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: advertise-opnsense
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - { key: somekey, operator: NotIn, values: ['never-used-value'] }
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: default
spec:
  blocks:
    - cidr: 10.25.0.0/24
