apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: opnsense
spec:
  peers:
    - peerConfig:
        peerASN: 64512
        neighborAddress: 10.0.0.1/32
      localASN: 64513
---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: advertise-opnsense
spec:
  to:
    peerSelectors:
      - matchLabels:
          name: opnsense
  serviceSelectors:
    - matchExpressions:
        - key: somekey
          operator: NotIn
          values:
            - "never-used-value"
  advertisePodCIDR: false
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: default
spec:
  blocks:
    - cidr: 10.25.0.0/24
