argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  global:
    domain: argocd.fincato.net
  configs:
    params:
      server.insecure: true
      application.namespaces: "default, kube-system, kube-public, kube-node-lease"
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      tls: true
