argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  global:
    domain: argocd.fincato.net
  configs:
    params:
      server.insecure: true
      application.namespaces: "*"
    cm:
      create: true
      resource.customizations: |
        Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      tls: false
