argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  global:
    domain: argocd.fincato.net
  configs:
    params:
      server.insecure: true
      application.namespaces: "*"
    cm: 
      create: true
      resource.customizations: |
        networking.k8s.io/Ingress:
            health.lua: |
              hs = {}
              hs.status = "Healthy"
              return hs
      resource.exclusions: |
        - apiGroups:
            - cilium.io
          kinds:
            - CiliumIdentity
          clusters:
            - "*"
  server:
    ingress:
      enabled: true
      ingressClassName: cilium
      tls: false
