---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAXN/aomFK439d+tHhVr+4tMcwpG7X1MygaNkWhbqFLff8SkQ9MQ+R92m7RWPny/VgaymohhGBDRq06HpCRgh49TtrbSYCZ7GVjnoegQkbo0eAnnNkiqCm3Ay3UczD9V1vkG0m9/GXmRURUwHza6VyEKVSGB1/7QXIClDDJ2bn/TgOh9Tx/K+xy2Fnl7U9Vxm+wMtGL8xuqink2Udts6iNkc2AxJOewh7D3Bh6b+hCK0S75VBr9e8Wf0nGrMCquDYgERUsebkPWnDDJ0OWAbbfLkeMJTINYfeVPCKCPLE+8lbTIIb0nGAST1bj1LcXQ9EwzpyxkHuLrFTs7dmSimqHs3sCQ7+dJZEPrb7dSedeD7MefhXlvVXYBoAQbA7nH2TiTqboagUgjsItEOBDPvlSe5erNOpxfu9Ye/VltW/f5u03yRHTSU4Ts+KRH20FO7nfCB8r/UVOp2M8kUGqnvhgdmGFYm5uTaZpJKVlLckVeJ4e8e9VMtXzGkapbCr78MgqFdTrl4ACkxTxnoHtfKpNQs8S++ATtMhBoWx3Uib7AieWVYEjVFCQT5pHtXYRyi2Hzm3j0Jd3fcyt9XkopwkaXrWX2UHEzVL8Zi6nbf1U1MKig4h41ribPgJpbJtuUP065n7mlUssCGMg3tUxCUKF1Ir4Ni+XrjG/kVvpiAkzc7XVbO0jcXn+D6UxEPb/Fmcsi+MjJmEAdx6iK3zQ0ixM2yBeyjIp2pBQdz0qbaT4yCoCRfAYr
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: cert-manager
    type: Opaque
