---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBwb8pZCEKILoI7yeiHsyyw7Ers25Xe5U9kt7q397RFXyopxld4+wPbj70S46e75cQh/6Pn0f+anJHaArvZGk+PCzV2kY9BHVA0I+8ORyidbJbL7Hs8Bw1TQ+fNx5DLu1QbK6u1FSnfHIUE5uQbmzRi1pEPQe+gc8IOkztyyh4N0F9W5Cnrb9qzJ22ZNjWEx9Ejvdpsx47aa3BDDWemQs7LhL7pAxJJ7vHFDmU/j9c+6+clIkgBwBcUvdxDNZPT2EUNI+KdR6CJ1jadix//HxVxFoiEwLAfyZRqQDIL+BwMfWGE4S2xZUdMBdebqje9b0uwxlr6Dk01ZNgzTvpOKiqq8XAfqomVOU/tn5ZrNAKMMjzje/Pw/VX4NgpIPtyluFWkLp4F4sKxDNR+VUnACKYzXWUMXt90lX75FSFjMpcYnU7i1EzKeS0lfcUXu6h3KF3/IBxmNVAbV2mZIUoMI6EKvWK3y6GIBkQr6N5xhX1FBrJ40OApUUxb2o/gzoO3DrU8g/hkl32JeumgOnfIaxhNbGcGdd051OOyJcuig0LpDMErg/6gHcYrFt3Y4bw4WA6TwJEK+AKl7R+3+ExTOvP+opCFD6JDOKrpbg3PKsDAFvGMurLZ1u6Cb4F/uyo1GxKMQK0p2WLdwEh1U6S9SH7UkzcAknTHxcfEuz77j9CagZP0OanXfBjoBby5EoqG+83HKp0nFmeie+3hSgDSxkgK4LT46d+bXjPdOpqhDquH1ovGR3qkuqsR
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: cert-manager
    type: Opaque
