---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.authentik.clientSecret: AgCyfJ7wCeU2pRyhTLt4cownbFJO/j0pbHJM88LJWv2qqVQwViyjQBtpBNqN9YeEDmIxzYyLDUhrTcvIu+YF8Gy7LcTTL1BDphcQpMF1BdDUHp6ZbZe3pqtd3xx3wiCoCXC7k5bcxiv+VNnEZF2eqSjQG0OOIytD9GbjDBieeLO/MNIiHtkJP6i16JAEvmGSNp3p7NfasdBBObTFocwYLSdyqyK0UQth50DVrzX77MeGaGGmUGOu7XHVrRfeThx0EQqQyjc2IBsjshfNria9O4lUUeOdenzt8R9BkZdTzHm6M0QVMZh3xnY2MSCuctk1oJJzghJ3rqJRgBWLoozDcgc3xloD1y8bIqZxqCKAX4y/v7g1sYQVOwS4lWD37sJFDaB9v8VmV5dCj269tfB1y1aaW8GMULuTIWUUsuay7OyWjPhKBxJAy6UXTV0EBWJ0YZwyaSDJpNuQ6cH7SCqz3rw0vF4k3oQ5NNW2x5c1snQDV1mgZ0y4eYgdangFLHIFhZqiQjAGQeW99//Lsq/fzXQ0Vf/01k7WLBNF2zurrfiSKbi+yJz9eVwt9WQppZ48Em9xM5OLXpZAfrHtt5HbvxPz3w78G4Up2YOaGcbfcddWoHBfownOCXN6o6Nj6dQZDCNT9JtpzqXTrHJtSgNkDyeIgPX1+yhg0h1NmNRmj9eyUJDFAUlsbyBHksmd7Dn/P9OGVOVVfo8oAGp0ASnvQ5E1f3cseBw3YRSwBMgSnA+cS/ORtLizNfzkA1dgrUEbAlFs2lEgzyvNwh6Q/HQNEYZrcMEpmhE7LIx+oblD6v1zcbHpF34i9VpI/muXaH+hQ0ek0sARuhVpWySaHyai8i3ujIOlovMM8/Env7LHMuAgIw==
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: argocd
    type: Opaque
