---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgA53B6fPDnji433Ti2ybC85tpOL+lE4m/v7E2nzZ3pBb0TeQFsR+5KqXcWtjhh8+G1C1pA9wCh27gt5XLlWGp8ONBwAvpVf5a6t0svtYhn0+mdQiqnV9p1mLCksSGtG+AZQRXLCnwSEL3Y1s+R0pAc7/ID0otbRb4zb9aquLLMh8wYvMh4TzcNQqwilmDFFlnfTg+Y1fx78kOpUjW8vKv6GNtYcaOiDQo9pKEd4BNfwos/uF2LO2VHobBUCCBR1cY3r+SgOwpl/xqu8yLXtlnVvasmhXIpJVJxWeT/2fEVDxX09DSbAw/qZ+8L8SEHIYRpr7IDNbVDDCCadfJ6rHTJ8r7fNqu6VsQAjphQw6WzyFteoljAMNQc4WqT2sMoHDO1Yyl5clz8v4XlwSt2mKO6J6d76XMv4LgDWoozdDhtZnbLAefCwqTaMijLoIyDHyJsMSK8U2odg0MCDPcVLp3ClxJZ8hFJcodSQ21ucbSFgllTqDnUfs/X/2u11vrlFbcJAkl3E37EF0PlhaVGYZ7qrFGGqplR0Swuu29WQeS3cu35FmC/EjEoyi7jh4ZXlGuFdJUmK957pzH08holoWTq+PWog+ZHS9JQggDFuFIaX7WesjwDlhK/e2lDuyCnytj4h17gdACU03n6/h2yoSpRehhFuh3YDjlJZtTkbwnyj7rLbfd0ibDXWztmDwkH2qFlOpBJIvTAHyNIGCmFCVyyMuuzQWqao/eNY4Rxy/2sjlTKoJ2JEXbeD9Dgf45ZqEBQL2fcZpsammJ0JT4+7sEFpPt85hIzvL+ma4ucSBppTsLdN2FNaXuSuUMmr9yRDQ5sKZdtbwfp2iuFcHWCiwb6eDyfunK9ivRI7R0EoVi5F3w==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
    type: Opaque
